/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GapAnalysisRouteImport } from './routes/gap-analysis'
import { Route as InterventionsRouteImport } from './routes/interventions'
import { Route as MySchoolRouteImport } from './routes/my-school'
import { Route as PriorityRouteImport } from './routes/priority'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GapAnalysisRoute = GapAnalysisRouteImport.update({
  id: '/gap-analysis',
  path: '/gap-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const InterventionsRoute = InterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => rootRouteImport,
} as any)
const MySchoolRoute = MySchoolRouteImport.update({
  id: '/my-school',
  path: '/my-school',
  getParentRoute: () => rootRouteImport,
} as any)
const PriorityRoute = PriorityRouteImport.update({
  id: '/priority',
  path: '/priority',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/dashboard': typeof DashboardRoute
  '/gap-analysis': typeof GapAnalysisRoute
  '/interventions': typeof InterventionsRoute
  '/my-school': typeof MySchoolRoute
  '/priority': typeof PriorityRoute
  '/reports': typeof ReportsRoute
  '/requirements': typeof RequirementsRoute
  '/schools': typeof SchoolsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/dashboard': typeof DashboardRoute
  '/gap-analysis': typeof GapAnalysisRoute
  '/interventions': typeof InterventionsRoute
  '/my-school': typeof MySchoolRoute
  '/priority': typeof PriorityRoute
  '/reports': typeof ReportsRoute
  '/requirements': typeof RequirementsRoute
  '/schools': typeof SchoolsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/dashboard': typeof DashboardRoute
  '/gap-analysis': typeof GapAnalysisRoute
  '/interventions': typeof InterventionsRoute
  '/my-school': typeof MySchoolRoute
  '/priority': typeof PriorityRoute
  '/reports': typeof ReportsRoute
  '/requirements': typeof RequirementsRoute
  '/schools': typeof SchoolsRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessments'
    | '/dashboard'
    | '/gap-analysis'
    | '/interventions'
    | '/my-school'
    | '/priority'
    | '/reports'
    | '/requirements'
    | '/schools'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessments'
    | '/dashboard'
    | '/gap-analysis'
    | '/interventions'
    | '/my-school'
    | '/priority'
    | '/reports'
    | '/requirements'
    | '/schools'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/assessments'
    | '/dashboard'
    | '/gap-analysis'
    | '/interventions'
    | '/my-school'
    | '/priority'
    | '/reports'
    | '/requirements'
    | '/schools'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentsRoute: typeof AssessmentsRoute
  DashboardRoute: typeof DashboardRoute
  GapAnalysisRoute: typeof GapAnalysisRoute
  InterventionsRoute: typeof InterventionsRoute
  MySchoolRoute: typeof MySchoolRoute
  PriorityRoute: typeof PriorityRoute
  ReportsRoute: typeof ReportsRoute
  RequirementsRoute: typeof RequirementsRoute
  SchoolsRoute: typeof SchoolsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gap-analysis': {
      id: '/gap-analysis'
      path: '/gap-analysis'
      fullPath: '/gap-analysis'
      preLoaderRoute: typeof GapAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interventions': {
      id: '/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof InterventionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-school': {
      id: '/my-school'
      path: '/my-school'
      fullPath: '/my-school'
      preLoaderRoute: typeof MySchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priority': {
      id: '/priority'
      path: '/priority'
      fullPath: '/priority'
      preLoaderRoute: typeof PriorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentsRoute: AssessmentsRoute,
  DashboardRoute: DashboardRoute,
  GapAnalysisRoute: GapAnalysisRoute,
  InterventionsRoute: InterventionsRoute,
  MySchoolRoute: MySchoolRoute,
  PriorityRoute: PriorityRoute,
  ReportsRoute: ReportsRoute,
  RequirementsRoute: RequirementsRoute,
  SchoolsRoute: SchoolsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
